use crate::cmake::discover_compile_database;
use crate::debug::log_message;
use crate::environment::discover_msvc_environment;
use crate::environment::tools::{ZedCommandRunner, require_clangd};
use crate::environment::vswhere::discover_visual_studio;
use crate::error::{ToolkitError, ToolkitResult};
use crate::lsp::clangd_config::ClangdConfigInput;
use crate::lsp::workspace_config::{ClangdFileDecision, decide_clangd_file};
use zed_extension_api as zed;

pub const LANGUAGE_SERVER_ID: &str = "msvc-cpp-clangd";

pub fn clangd_args() -> Vec<String> {
    vec![
        "--header-insertion=never".to_string(),
        "--log=verbose".to_string(),
    ]
}

pub fn validate_language_server_id(id: &str) -> ToolkitResult<()> {
    if id == LANGUAGE_SERVER_ID {
        Ok(())
    } else {
        Err(ToolkitError::UnsupportedLanguageServer(id.to_string()))
    }
}

pub fn build_clangd_command(command: String, env: Vec<(String, String)>) -> zed::Command {
    zed::Command {
        command,
        args: clangd_args(),
        env,
    }
}

pub fn command_from_worktree(worktree: &zed::Worktree) -> ToolkitResult<zed::Command> {
    log_message("looking up clangd via worktree.which(\"clangd\")");
    let clangd = require_clangd(worktree.which("clangd"))?;
    log_message(&format!("clangd found: {clangd}"));
    Ok(build_clangd_command(clangd, worktree.shell_env()))
}

pub fn prepare_workspace_config(
    root_path: &str,
    existing_clangd: Option<String>,
    runner: &impl crate::environment::tools::CommandRunner,
) -> ToolkitResult<()> {
    log_message(&format!(
        "prepare_workspace_config started: root={root_path}"
    ));

    if let Some(contents) = &existing_clangd {
        log_message(&format!(
            "existing .clangd found; bytes={}, preview={}",
            contents.len(),
            one_line_preview(contents)
        ));
        if !contents.contains("# 由 Zed MSVC C++ Assistant 自动生成。") {
            log_message("skipping generated .clangd because workspace already provides one");
            return Ok(());
        }
    }

    let compile_db_path = ensure_compile_database(root_path, runner);
    match &compile_db_path {
        Some(path) => log_message(&format!("compile_commands.json detected in: {path}")),
        None => log_message("compile_commands.json not detected in root or build/"),
    }

    if existing_clangd.is_some() {
        if compile_db_path.is_some() {
            log_message(
                "existing .clangd was generated by this extension; refreshing it with current compile database path",
            );
        } else {
            log_message(
                "existing .clangd was generated by this extension; refreshing it without compile database path",
            );
        }
    }

    write_generated_clangd(root_path, compile_db_path, runner)
}

fn write_generated_clangd(
    root_path: &str,
    compile_db_path: Option<String>,
    runner: &impl crate::environment::tools::CommandRunner,
) -> ToolkitResult<()> {
    log_message("discovering MSVC environment for generated .clangd");
    let environment = discover_msvc_environment(runner)?;
    log_message(&format!(
        "MSVC environment discovered: vs_root={}, msvc_include={}, sdk_include_count={}",
        environment.visual_studio_root,
        environment.msvc_include,
        environment.sdk_includes.len()
    ));
    let input = ClangdConfigInput {
        msvc_include: environment.msvc_include,
        sdk_includes: environment.sdk_includes,
        compile_database_path: compile_db_path,
    };

    match decide_clangd_file(root_path, None, &input) {
        ClangdFileDecision::Create { contents, .. } => {
            log_message(&format!("generated .clangd content:\n{contents}"));
            match write_clangd_file(root_path, &contents, runner) {
                Ok(()) => log_message("wrote generated .clangd to workspace root"),
                Err(error) => {
                    crate::debug::log_error("failed to write generated .clangd", &error);
                    log_message("continuing without blocking clangd startup");
                }
            }
            Ok(())
        }
        ClangdFileDecision::PreserveExisting { .. } => {
            log_message("preserving existing .clangd");
            Ok(())
        }
    }
}

fn ensure_compile_database(
    root_path: &str,
    runner: &impl crate::environment::tools::CommandRunner,
) -> Option<String> {
    if let Some(path) = discover_compile_database_from_host(root_path, runner) {
        return Some(path);
    }

    if !host_path_exists(runner, &join_windows_path(root_path, "CMakeLists.txt")).unwrap_or(false) {
        log_message("CMakeLists.txt not found; skipping CMake configure");
        return None;
    }

    log_message("compile_commands.json missing; running CMake configure for build/");
    if let Err(error) = run_cmake_configure_for_compile_database(root_path, runner) {
        crate::debug::log_error("CMake configure failed", &error);
        return None;
    }
    if let Err(error) = run_cmake_autogen_targets(root_path, runner) {
        crate::debug::log_error("CMake autogen target failed", &error);
    }

    let discovered = discover_compile_database_from_host(root_path, runner);
    match &discovered {
        Some(path) => log_message(&format!(
            "compile_commands.json generated by CMake configure in: {path}"
        )),
        None => log_message(
            "CMake configure completed but build/compile_commands.json is still missing",
        ),
    }
    discovered
}

fn discover_compile_database_from_host(
    root_path: &str,
    runner: &impl crate::environment::tools::CommandRunner,
) -> Option<String> {
    if let Some(path) = discover_compile_database(root_path) {
        return Some(path);
    }

    let root_db = join_windows_path(root_path, "compile_commands.json");
    if host_path_exists(runner, &root_db).unwrap_or(false) {
        return Some(root_path.to_string());
    }

    let build_dir = join_windows_path(root_path, "build");
    let build_db = join_windows_path(&build_dir, "compile_commands.json");
    if host_path_exists(runner, &build_db).unwrap_or(false) {
        return Some(build_dir);
    }

    None
}

fn host_path_exists(
    runner: &impl crate::environment::tools::CommandRunner,
    path: &str,
) -> ToolkitResult<bool> {
    let escaped_path = powershell_single_quote(path);
    let script = format!(
        "$ErrorActionPreference='Stop'; if (Test-Path -LiteralPath {escaped_path}) {{ 'true' }} else {{ 'false' }}"
    );
    let args = vec!["-NoProfile".to_string(), "-Command".to_string(), script];
    let output = runner.run_command("powershell", &args)?;
    let stdout = crate::environment::tools::ensure_success("powershell", output)?;
    Ok(stdout.trim().eq_ignore_ascii_case("true"))
}

fn join_windows_path(root_path: &str, child: &str) -> String {
    format!(
        "{}\\{}",
        root_path.trim_end_matches(['\\', '/'].as_slice()),
        child.trim_start_matches(['\\', '/'].as_slice())
    )
}

fn run_cmake_configure_for_compile_database(
    root_path: &str,
    runner: &impl crate::environment::tools::CommandRunner,
) -> ToolkitResult<()> {
    let visual_studio_root = discover_visual_studio(runner)?;
    let vs_dev_cmd = join_windows_path(&visual_studio_root, r"Common7\Tools\VsDevCmd.bat");
    let build_dir = join_windows_path(root_path, "build");
    let cmake_args = vec![
        "-S".to_string(),
        root_path.to_string(),
        "-B".to_string(),
        build_dir.clone(),
        "-G".to_string(),
        "Ninja".to_string(),
        "-DCMAKE_C_COMPILER=cl".to_string(),
        "-DCMAKE_CXX_COMPILER=cl".to_string(),
        "-DCMAKE_BUILD_TYPE=Debug".to_string(),
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON".to_string(),
    ];
    let cmake_command = format!(
        "cmake {}",
        cmake_args
            .iter()
            .map(|arg| cmd_quote(arg))
            .collect::<Vec<_>>()
            .join(" ")
    );
    let cmd_line = format!(
        "call {} -arch=x64 -host_arch=x64 && {cmake_command}",
        cmd_quote(&vs_dev_cmd)
    );
    let script = format!(
        "$ErrorActionPreference='Stop'; & cmd.exe /S /C {}",
        powershell_single_quote(&cmd_line)
    );
    log_message(&format!(
        "running CMake configure through VS developer environment: {cmake_command}"
    ));
    let args = vec!["-NoProfile".to_string(), "-Command".to_string(), script];
    let output = runner.run_command("powershell", &args)?;
    crate::environment::tools::ensure_success("powershell", output).map(|_| ())
}

fn run_cmake_autogen_targets(
    root_path: &str,
    runner: &impl crate::environment::tools::CommandRunner,
) -> ToolkitResult<()> {
    let Some(target) = first_autogen_target(root_path, runner)? else {
        log_message("no CMake *_autogen target found; skipping Qt autogen");
        return Ok(());
    };

    let build_dir = join_windows_path(root_path, "build");
    let args = vec![
        "--build".to_string(),
        build_dir,
        "--target".to_string(),
        target.clone(),
    ];
    log_message(&format!("running CMake autogen target: {target}"));
    let output = runner.run_command("cmake", &args)?;
    crate::environment::tools::ensure_success("cmake", output).map(|_| ())
}

fn first_autogen_target(
    root_path: &str,
    runner: &impl crate::environment::tools::CommandRunner,
) -> ToolkitResult<Option<String>> {
    let build_ninja = join_windows_path(&join_windows_path(root_path, "build"), "build.ninja");
    let escaped_path = powershell_single_quote(&build_ninja);
    let script = format!(
        "$ErrorActionPreference='Stop'; if (!(Test-Path -LiteralPath {escaped_path})) {{ return }}; \
         Select-String -LiteralPath {escaped_path} -Pattern '^build ([^: ]+_autogen): phony' | \
         ForEach-Object {{ $_.Matches[0].Groups[1].Value }} | Select-Object -First 1"
    );
    let args = vec!["-NoProfile".to_string(), "-Command".to_string(), script];
    let output = runner.run_command("powershell", &args)?;
    let stdout = crate::environment::tools::ensure_success("powershell", output)?;
    Ok(stdout.lines().map(str::trim).find(|line| !line.is_empty()).map(ToOwned::to_owned))
}

pub fn prepare_workspace_config_from_worktree(worktree: &zed::Worktree) -> ToolkitResult<()> {
    let clangd_contents = worktree.read_text_file(".clangd").ok();
    log_message(&format!(
        "worktree .clangd read result: exists={}",
        clangd_contents.is_some()
    ));
    prepare_workspace_config(&worktree.root_path(), clangd_contents, &ZedCommandRunner)
}

fn write_clangd_file(
    root_path: &str,
    contents: &str,
    runner: &impl crate::environment::tools::CommandRunner,
) -> ToolkitResult<()> {
    let path = format!(
        "{}\\.clangd",
        root_path.trim_end_matches(['\\', '/'].as_slice())
    );
    let escaped_path = powershell_single_quote(&path);
    let escaped_contents = powershell_single_quote(contents);
    let script = format!(
        "$ErrorActionPreference='Stop'; Set-Content -LiteralPath {escaped_path} -Encoding UTF8 -Value {escaped_contents}"
    );
    let args = vec!["-NoProfile".to_string(), "-Command".to_string(), script];
    let output = runner.run_command("powershell", &args)?;
    crate::environment::tools::ensure_success("powershell", output).map(|_| ())
}

fn powershell_single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn cmd_quote(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}

fn one_line_preview(contents: &str) -> String {
    const MAX_PREVIEW_CHARS: usize = 500;

    let mut preview = String::new();
    for character in contents.chars().take(MAX_PREVIEW_CHARS) {
        if character.is_control() {
            preview.push(' ');
        } else {
            preview.push(character);
        }
    }

    if contents.chars().count() > MAX_PREVIEW_CHARS {
        preview.push_str("...");
    }

    preview
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::environment::tools::CommandOutput;
    use std::cell::RefCell;
    use std::collections::VecDeque;

    #[test]
    fn clangd_args_disable_header_insertion() {
        assert_eq!(
            clangd_args(),
            vec!["--header-insertion=never", "--log=verbose"]
        );
    }

    #[test]
    fn accepts_expected_language_server_id() {
        assert_eq!(validate_language_server_id("msvc-cpp-clangd"), Ok(()));
    }

    #[test]
    fn rejects_unexpected_language_server_id() {
        let error = validate_language_server_id("other-lsp").unwrap_err();

        assert_eq!(
            error,
            ToolkitError::UnsupportedLanguageServer("other-lsp".to_string())
        );
    }

    #[test]
    fn skips_environment_discovery_when_clangd_config_exists() {
        struct PanickingRunner;

        impl crate::environment::tools::CommandRunner for PanickingRunner {
            fn run_command(
                &self,
                _command: &str,
                _args: &[String],
            ) -> ToolkitResult<crate::environment::tools::CommandOutput> {
                panic!("runner should not be used when .clangd exists");
            }
        }

        assert_eq!(
            prepare_workspace_config(
                "C:/repo",
                Some("CompileFlags: {}".to_string()),
                &PanickingRunner
            ),
            Ok(())
        );
    }

    struct QueueRunner {
        outputs: RefCell<VecDeque<CommandOutput>>,
        calls: RefCell<Vec<(String, Vec<String>)>>,
    }

    impl QueueRunner {
        fn new(outputs: impl IntoIterator<Item = CommandOutput>) -> Self {
            Self {
                outputs: RefCell::new(outputs.into_iter().collect()),
                calls: RefCell::new(Vec::new()),
            }
        }
    }

    impl crate::environment::tools::CommandRunner for QueueRunner {
        fn run_command(&self, command: &str, args: &[String]) -> ToolkitResult<CommandOutput> {
            self.calls
                .borrow_mut()
                .push((command.to_string(), args.to_vec()));
            self.outputs
                .borrow_mut()
                .pop_front()
                .ok_or_else(|| ToolkitError::IoMessage("unexpected command".to_string()))
        }
    }

    #[test]
    fn continues_when_clangd_config_is_missing() {
        let runner = QueueRunner::new([
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "C:\\VS\\2022\\Community\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "14.38.33130\n14.40.33807\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "10.0.19041.0\n10.0.22621.0\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "ucrt\num\nshared\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            },
        ]);

        let result = prepare_workspace_config("C:/repo", None, &runner);

        assert_eq!(result, Ok(()));
        assert!(runner.calls.borrow().iter().any(|(command, args)| {
            command == "powershell"
                && args
                    .iter()
                    .any(|arg| arg.contains("Set-Content -LiteralPath 'C:/repo\\.clangd'"))
        }));
    }

    #[test]
    fn runs_cmake_configure_when_compile_database_is_missing() {
        use std::fs;
        use std::sync::atomic::{AtomicUsize, Ordering};

        static TEST_COUNTER: AtomicUsize = AtomicUsize::new(0);
        let test_id = TEST_COUNTER.fetch_add(1, Ordering::SeqCst);
        let temp_dir = std::env::temp_dir().join(format!(
            "zed-msvc-cmake-configure-{}-{}",
            std::process::id(),
            test_id
        ));
        fs::create_dir_all(&temp_dir).unwrap();
        fs::write(
            temp_dir.join("CMakeLists.txt"),
            "cmake_minimum_required(VERSION 3.20)\nproject(test)\n",
        )
        .unwrap();

        let runner = QueueRunner::new([
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "true\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "C:\\VS\\2022\\Community\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "test_autogen\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "false\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "C:\\VS\\2022\\Community\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "14.40.33807\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "10.0.22621.0\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "ucrt\num\nshared\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            },
        ]);

        let result = prepare_workspace_config(
            temp_dir.to_str().expect("temp path should be valid UTF-8"),
            None,
            &runner,
        );

        assert_eq!(result, Ok(()));
        assert!(runner.calls.borrow().iter().any(|(command, args)| {
            command == "powershell"
                && args
                    .iter()
                    .any(|arg| arg.contains("VsDevCmd.bat")
                        && arg.contains("-DCMAKE_CXX_COMPILER=cl")
                        && arg.contains("-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"))
        }));
        assert!(runner.calls.borrow().iter().any(|(command, args)| {
            command == "cmake"
                && args.iter().any(|arg| arg == "--target")
                && args.iter().any(|arg| arg == "test_autogen")
        }));

        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn continues_when_compilation_database_is_present_in_root() {
        // 这个测试需要实际文件系统，创建临时目录
        use std::fs;
        use std::sync::atomic::{AtomicUsize, Ordering};

        static TEST_COUNTER: AtomicUsize = AtomicUsize::new(0);
        let test_id = TEST_COUNTER.fetch_add(1, Ordering::SeqCst);

        let temp_dir = std::env::temp_dir().join(format!(
            "zed-msvc-integration-root-{}-{}",
            std::process::id(),
            test_id
        ));
        fs::create_dir_all(&temp_dir).unwrap();

        // 创建 compile_commands.json
        fs::write(temp_dir.join("compile_commands.json"), r#"[]"#).unwrap();

        let runner = QueueRunner::new([
            CommandOutput {
                status: Some(0),
                stdout: "C:\\VS\\2022\\Community\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "14.40.33807\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "10.0.22621.0\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "ucrt\num\nshared\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            },
        ]);

        let result = prepare_workspace_config(
            temp_dir.to_str().expect("temp path should be valid UTF-8"),
            None,
            &runner,
        )
        .unwrap();

        assert_eq!(result, ());

        // 清理
        let _ = fs::remove_dir_all(&temp_dir);
    }

    #[test]
    fn continues_when_compilation_database_is_present_in_build_subdirectory() {
        use std::fs;
        use std::sync::atomic::{AtomicUsize, Ordering};

        static TEST_COUNTER: AtomicUsize = AtomicUsize::new(0);
        let test_id = TEST_COUNTER.fetch_add(1, Ordering::SeqCst);

        let temp_dir = std::env::temp_dir().join(format!(
            "zed-msvc-integration-build-{}-{}",
            std::process::id(),
            test_id
        ));
        fs::create_dir_all(&temp_dir).unwrap();

        // 创建 build 子目录和 compile_commands.json
        let build_dir = temp_dir.join("build");
        fs::create_dir_all(&build_dir).unwrap();
        fs::write(build_dir.join("compile_commands.json"), r#"[]"#).unwrap();

        let runner = QueueRunner::new([
            CommandOutput {
                status: Some(0),
                stdout: "C:\\VS\\2022\\Community\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "14.40.33807\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "10.0.22621.0\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: "ucrt\num\nshared\n".to_string(),
                stderr: String::new(),
            },
            CommandOutput {
                status: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            },
        ]);

        let result = prepare_workspace_config(
            temp_dir.to_str().expect("temp path should be valid UTF-8"),
            None,
            &runner,
        )
        .unwrap();

        assert_eq!(result, ());

        // 清理
        let _ = fs::remove_dir_all(&temp_dir);
    }
}
